spring.data.mongodb.host: ${MONGO_HOST:localhost}
spring.data.mongodb.port: ${MONGO_PORT:27017}
spring.data.mongodb.database: miworld_master
spring.data.mongodb.password: ${MONGO_PASS:miworld}
spring.data.mongodb.username: ${MONGO_USER:root}
logging.level.ROOT: INFO
#spring.data.mongodb.uri: mongodb://root:miworld@localhost:27017/users
server.servlet.context-path: /auth